name: mini-game-service
services:
  node:
    image: node:18
    container_name: mini-game-api-node
    working_dir: /usr/src/app
    build: .
    volumes:
      - .:/usr/src/app
    restart: always
    ports:
      - "3002:3000"
    depends_on:
      db:
        condition: service_healthy
    command: npm run start

  db:
    image: mysql:8
    container_name: mini-game-api-mysql
    restart: always
    environment:
      MYSQL_DATABASE: game_service
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - /mnt/storage/mini-game-be-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  mini_game_mongo_data: