name: mini-game-service

services:
  node:
    image: node:20
    container_name: mini-game-api-node
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    entrypoint: ["./docker-entrypoint.sh"]
    restart: always
    ports:
      - "3002:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.18
    container_name: mini-game-api-mongo
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mini_game_mongo_data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: test $$(mongosh --eval "rs.initiate()" | grep 'ok') == 1
      interval: 10s
      timeout: 5s
      retries: 50

volumes:
  mini_game_mongo_data: