name: mini-game-service

services:
  node:
    image: node:18
    container_name: mini-game-api-node
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: >
      bash -c "npm install &&
        npx prisma db push &&
        node prisma/seeders/seed.js &&
        npx nodemon index.js"
    restart: always
    ports:
      - "3002:3000"
    depends_on:
      - mongo

  mongo:
  image: arm64v8/mongo:6
  container_name: mini-game-api-mongo
  restart: always
  environment:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: linux001
    MONGO_INITDB_DATABASE: mini_game_db
  ports:
    - "27019:27017"
  volumes:
    - mini_game_mongo_data:/data/db


volumes:
  mini_game_mongo_data:
